### ISSUE TITLE
感谢作者提供这么好的应用程序，一直在找这种手机电脑互传文件的Web端

### ISSUE THREAD

**Issue by nbotu** [TransparentLC/cloud-clipboard#1]
首先感谢作者，我是在Linux上运行的，根据你的使用说明，我完成了环境配置，php是7.2的，开启了swoole扩展。但是运行后报错如下：
![image](https://user-images.githubusercontent.com/64408436/80587167-a93f5580-8a48-11ea-91e3-310182727d0f.png)

网页访问Web端无法打开，配置文件我只改了我本地ip和端口，如下:

![image](https://user-images.githubusercontent.com/64408436/80587270-cffd8c00-8a48-11ea-9e71-3840f6a508a8.png)

本人刚接触PHP不是很懂，还请作者看一下这报错咋回事，最后再次谢谢作者提供这个方便的传输文件应用！

**Comment by TransparentLC** [comment]
我自己在这几个环境下测试了一下，都是可以正常运行的……
* Swoole 官方提供的 Cygwin 整合包（PHP 7.1 + Swoole 4.5.0 RC1）
* WSL 的 Ubuntu 18.04 + PHP 7.4 + Swoole 4.5.0 RC1
* CentOS 7 + PHP 7.4 + Swoole 4.4.16

**Comment by TransparentLC** [comment]
已添加 NodeJS 版服务端，可以试试看
