### ISSUE TITLE
我用arm 的debian 网页不显示

### ISSUE THREAD

**Issue by gerenzhuyi** [TransparentLC/cloud-clipboard#10]
这个是不是只支持X86的 我想问问怎么让他在arm上运行

**Comment by TransparentLC** [comment]
有没有出错信息？

**Comment by gerenzhuyi** [comment]
想想你回复 因为我不是专业的 所以请尽量是的清楚点谢谢   命令行报错 Authorization code is disabled.

网页只显示 Not Found

**Comment by TransparentLC** [comment]
“Authorization code is disabled.”不算报错，只是没启用密码认证功能，对于这个的说明可以参见 README。

运行的时候“Available at:”会按照网卡分类输出很多地址，但是你需要选择在同一个局域网下的地址。比如在连着 Wi-Fi 的电脑上运行这个然后输出的地址是“WLAN: http://192.168.0.101:9501 ”和“Loopback Pseudo-Interface: http://127.0.0.1:9501 ”，想要用连着同一个路由器的 Wi-Fi 的手机打开，那应该使用 http://192.168.0.101:9501 而不是后者。

CPU 架构可能会有影响，因为给图片生成缩略图用到了 sharp 这个库，按照[文档](https://sharp.pixelplumbing.com/install#prebuilt-binaries)上的说法对于 Linux 只有 ARM64 才有完整的预编译版，而对于 ARMv7 和 ARMv6 是没有的。不过我没测试过 sharp 用不了是不是就会显示 not found 还是说直接跑不起来……

**Comment by gerenzhuyi** [comment]
我是用armV7旧手机运行的 看来是架构原因 我也算帮你只是了解 哈哈哈
