### ISSUE TITLE
4096字数限制怎么修改？

### ISSUE THREAD

**Issue by superck110** [TransparentLC/cloud-clipboard#11]
感谢作者搞了这么实用的工具。我在局域网群晖套件docker里pull的镜像文件，这个4096字数限制有没有办法修改呢。

**Comment by TransparentLC** [comment]
https://github.com/TransparentLC/cloud-clipboard#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%AF%B4%E6%98%8E
