### ISSUE TITLE
下载文件过大会不会有问题

### ISSUE THREAD

**Issue by TY88351** [TransparentLC/cloud-clipboard#14]
下载文件好像是先下到内存里，最后通过blob下载，这样如果文件很大，比如20G会不会出现内存不够的情况？能不能提供直连的方式，这样如果是视频或者图片，也能够直接在浏览器中查看而不用下载，特别是对于大视频不能直接查看麻烦很多

**Comment by TransparentLC** [comment]
咦我当时怎么会想着先下到 Blob 再保存到硬盘上的（

改成 `<a href="..." download>` 之后点击就可以直接下载了，也可以右键复制链接或者在新标签页中打开（比如你说的要直接查看视频的情况），为了这个还顺便把分片下载也加上了，可以试试看。

虽然理论上可行，不过我没有用这个工具传过 20 GB 的文件……
