### ISSUE TITLE
ssl问题

### ISSUE THREAD

**Issue by TY88351** [TransparentLC/cloud-clipboard#15]
如果外部nginx使用了ssl，转发之后虽然能使用https，但是ws仅仅由服务端判断，如果服务端没有配置证书的，则还是没有使用到ssl，建议用ws还是wss加以浏览器端判断，作为请求参数来控制使用ws还是wss。或者可以加个配置参数强制使用ws还是wss

**Comment by TransparentLC** [comment]
已经在 config 里添加了 `forceWss` 选项，如果是 `true` 的话即使 `key` 和 `cert` 是空的也会让前端使用 WSS 连接。应该不会有设了 `key` 和 `cert` 又要用 WS 连接的情况吧……
