### ISSUE TITLE
node 18以上版本编译失败，node16可以编译成功，但会报错。

### ISSUE THREAD

**Issue by sonicno1** [TransparentLC/cloud-clipboard#20]
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($grid-gutter, 3) or calc($grid-gutter / 3)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ?
65 │     'md': $grid-gutter / 3,
   │           ^^^^^^^^^^^^^^^^
   ?
    node_modules/vuetify/src/styles/settings/_variables.scss 65:11                      @import
    node_modules/vuetify/src/styles/settings/_index.sass 1:9                            @import
    node_modules/vuetify/src/styles/styles.sass 2:9                                     @import
    node_modules/vuetify/src/components/VCalendar/mixins/calendar-with-events.sass 1:9  root stylesheet

Warning: 1 repetitive deprecation warnings omitted.

**Comment by TransparentLC** [comment]
Node.js 17 及以上编译失败的解决办法请看 README。

这些 Warning 不影响编译。
