### ISSUE TITLE
cf tunnel 穿透有问题

### ISSUE THREAD

**Issue by hausen1012** [TransparentLC/cloud-clipboard#24]
穿透后使用 https，但是还是发送 ws 请求，希望能根据协议自行判断 ws 或者 wss

**Comment by hausen1012** [comment]
那这样局域网没有https就不能用了呢。

**Comment by TransparentLC** [comment]
有道理，那么 `forceWss` 的设定就不需要了。

现在使用 http 访问的话就会使用 ws，使用 https 访问的话就会使用 wss。

**Comment by hausen1012** [comment]
太迅速了，大佬。非常感谢，你这个项目非常好用

**Comment by TransparentLC** [comment]
docker 镜像不是我维护的，可以帮你敲一下维护者 @law52525

**Comment by hausen1012** [comment]
哦哦。其实可以做一个自动化呢

**Comment by hausen1012** [comment]
而且似乎目前的dockerfile不适用了，升级node，不知道其他的依赖会不会有问题
![image](https://github.com/TransparentLC/cloud-clipboard/assets/50026605/a972c58f-f249-460c-b468-b374c56a54ae)

**Comment by hausen1012** [comment]
使用这个依然无法构建

```sh
FROM node:21.7.1
COPY . /app
WORKDIR /app/client
RUN npm install --registry=https://registry.npmmirror.com
RUN npm run build
WORKDIR /app/server-node
RUN npm install --registry=https://registry.npmmirror.com
EXPOSE 9501
CMD node main.js
```
