### ISSUE TITLE
支持用户管理功能

### ISSUE THREAD

**Issue by hausen1012** [TransparentLC/cloud-clipboard#27]
建议可以配置用户管理功能，因为云剪贴板做为一个剪贴板功能，剪贴板有可能是隐私内容，如果公开反而不好。

另一方面，剪贴板一般都是自己用，共用的可能性比较小，所以有必要用户登录只能看见自己的那部分内容。

虽然说这可以通过输入房间号实现区分不同的用户，但正如上面所说，剪贴板内容有可能是隐私内容，万一某个不小心被互联网爬虫爬到就不好了。

需要补充的一点是，虽然说可以使用 basic 认证来保证一定的安全，但是这样就不能分享给朋友使用了。

目前的想法是，支持用户登录，但是也保留公共的剪贴板。就像图床那样，可以配置是否为游客模式，不知道这样是否可行。

**Comment by TransparentLC** [comment]
有没有可能我做这个项目就是想要做到即开即用不想登录（笑

如果你自己的房间名称是一个不会被轻易遍历到的值，那除了你自己和部署剪贴板的人，其他人不可能接触到你的隐私内容。即使你泄露了自己的房间名称，也可以直接将所有内容删除然后再使用一个新的。
