### ISSUE TITLE
不支持npm反向代理？

### ISSUE THREAD

**Issue by ychun1234** [TransparentLC/cloud-clipboard#28]
docker方式安装，用http方式的IP+端口，访问没有问题，npm域名反向ssl证书代理无法连接，提示：“连接服务器失败，请点击工具栏上的“连接”图标重试”，但是web界面的主题内容已经显示出来了，不知道是什么原因，详见附件截图。
![捕获](https://github.com/TransparentLC/cloud-clipboard/assets/71625572/81e41100-6c4f-4eab-9e48-baa7f7c416a1)

**Comment by ychun1234** [comment]
配置文件设置forceWss为true没有作用；
临时解决办法：手动设置自签名证书，npm设置https代理。

**Comment by TransparentLC** [comment]
`forceWss` 这个选项已经取消了（#24）不知道你用的是这里的 Dockerfile 还是 Docker Hub 上的版本？如果是前者的话修改它不会有影响，会根据访问前端页面使用的是 http 还是 https 来选择使用 ws 或 wss。

因为你用的是自签名证书，我觉得也许是因为默认不被信任所以建立 wss 连接的时候被浏览器掐掉了。如果可以的话请附上
浏览器开发者工具“网络”部分的截图。

**Comment by TransparentLC** [comment]
我试了一下，Dockerfile 是可以正常使用的。

![](https://github.com/TransparentLC/cloud-clipboard/assets/47057319/fd936b01-a33a-45dc-8e89-3bc650e9b479)

**Comment by ychun1234** [comment]
好的，多谢。先继续使用自签名证书。后面有机会用ubuntu测试一下。
