### ISSUE TITLE
介绍中.有错别字.另外还有个使用中的bug

### ISSUE THREAD

**Issue by 307836997** [TransparentLC/cloud-clipboard#29]
配置文件说明中
"auth": false // 是否在连接时要求使用密码认证，falsy 值表示不使用
这一行.注释那里是不是错别字?额这是小问题
使用中我发现我用0开头的4位数密码这个docker项目就无限重启

**Comment by TransparentLC** [comment]
[假值 - MDN Web 文档术语表：Web 相关术语的定义 | MDN](https://developer.mozilla.org/zh-CN/docs/Glossary/Falsy)

如果写的是 `"auth": "0123"` 这样的话是可以正常运行的，你可能写成了 `"auth": 0123`，但是 JSON 不允许数值前面有多余的 0。

**Comment by 307836997** [comment]
> 不是错别字，参见[假值 - MDN Web 文档术语表：Web 相关术语的定义 | MDN](https://developer.mozilla.org/zh-CN/docs/Glossary/Falsy)
> 
> 如果写的是 `"auth": "0123"` 这样的话是可以正常运行的，你可能写成了 `"auth": 0123`，但是 JSON 不允许数值前面有多余的 0。

大佬有Q群之类的东西吗..菜鸡想请教下...

**Comment by TransparentLC** [comment]
没有。

有问题可以直接开 issue 询问。
