### ISSUE TITLE
希望打包一个Docker安装的版本

### ISSUE THREAD

**Issue by Theergold** [TransparentLC/cloud-clipboard#3]
想部署到NAS上,想要个Docker打包的版本,可以考虑出一个嘛

**Comment by TransparentLC** [comment]
我没有用过 Docker 啦……

不过参考“NodeJS 版服务端 从源代码运行”那里的命令，从[官方的 node 镜像](https://hub.docker.com/_/node)开始写一个 Dockerfile 应该不会很麻烦？

**Comment by TransparentLC** [comment]
有人写好了 dockerfile，如果你还在使用这个项目的话可以试试看：#8
