### ISSUE TITLE
反代后提示  连接服务器失败，请点击工具栏上的“连接”图标重试

### ISSUE THREAD

**Issue by 307836997** [TransparentLC/cloud-clipboard#30]
环境:群晖,docker部署
配置文件
`{
    "server": {
        "host": "127.0.0.1",
        "port": 9501,
        "wss": false,
        "history": 10,
        "auth": false
    },
    "text": {
        "limit": 4096
    },
    "file": {
        "expire": 3600,
        "chunk": 2097152,
        "limit": 2684354560
    }
}`
反代好后,可以正常访问页面,但是提示 连接服务器失败，请点击工具栏上的“连接”图标重试

**Comment by TransparentLC** [comment]
请附上从打开页面开始的浏览器开发者工具“网络”部分的截图。

**Comment by 307836997** [comment]
![clip01](https://github.com/TransparentLC/cloud-clipboard/assets/103431818/839df05f-c1aa-4868-9cc7-6f2b8cb72fb2)
这是点右上角重连的结果.

**Comment by TransparentLC** [comment]
你是用什么地址打开页面的？比如 127.0.0.1:9501 或者其他的 IP 地址或域名。上面对 /server 的请求返回的数据是什么？

另外你用的是 Dockerfile 还是 Docker Hub 上的那个比较旧的版本？

**Comment by 307836997** [comment]
域名打开的
我用的docker hub
dockerfile我不知道是什么.我是小白.
![clip01](https://github.com/TransparentLC/cloud-clipboard/assets/103431818/e8bcf0bf-24a4-4fc9-9b87-ecaf835be1bb)

**Comment by TransparentLC** [comment]
Docker Hub 的那个还是对反向代理有问题的版本，我更新之后它并没有跟着更新。参考 README 的“自己打包”或“从源代码运行”（不使用 docker）再试试看？

**Comment by 307836997** [comment]
额好吧.我学习下.

**Comment by 307836997** [comment]
> Docker Hub 的那个还是对反向代理有问题的版本，我更新之后它并没有跟着更新。参考 README 的“自己打包”或“从源代码运行”（不使用 docker）再试试看？

我想问一个小白的问题,github 上的项目 构建docker项目可以自动更新吗?如果不能自动更新.那它有没有办法 出了新版本提示我重新构建更新下.

**Comment by TransparentLC** [comment]
（我对 docker 不太熟悉，以下回答可能存在错误）

Docker Hub 是使用已经打包好的镜像，因此这个 repo 更新的话 Docker Hub 那边也需要重新打包上传。不过 README 里写的 `csmayi/lan-clip` 并不是我维护的，所以在上传者同步更新之前用这种方式部署的就是比 repo 内还要旧的版本。

刚刚看了一下，最近又有人打包了 [chenqiyux/lan-clip](https://hub.docker.com/r/chenqiyux/lan-clip)，也可以试试看？如果可以正常使用的话我会更新 README。

**Comment by 307836997** [comment]
> （我对 docker 不太熟悉，以下回答可能存在错误）
> 
> Docker Hub 是使用已经打包好的镜像，因此这个 repo 更新的话 Docker Hub 那边也需要重新打包上传。不过 README 里写的 csmayi/lan-clip 并不是我维护的，所以在上传者同步更新之前用这种方式部署的就是比 repo 内还要旧的版本。
> 
> 刚刚看了一下，最近又有人打包了 [chenqiyux/lan-clip](https://hub.docker.com/r/chenqiyux/lan-clip)，也可以试试看？如果可以正常使用的话我会更新 README。

部署成功了.一切正常.谢谢.
