### ISSUE TITLE
重启docker容器后,网页的历史记录就清空了 怎么设置不清空记录

### ISSUE THREAD

**Issue by 2606090723** [TransparentLC/cloud-clipboard#31]
重启docker容器后,网页的历史记录就清空了 怎么设置不清空记录

**Comment by TransparentLC** [comment]
#25

**Comment by 2606090723** [comment]
晓得了,我在一个公众号文章看的,文章上镜像是 
<img width="892" alt="image" src="https://github.com/TransparentLC/cloud-clipboard/assets/24692385/e6c59a12-82cb-4ee8-8bfb-67ea47f2e266">
这是一年前的镜像了   现在是chenqiyux/lan-clip:latest
