### ISSUE TITLE
文件传输的原理

### ISSUE THREAD

**Issue by mapleie** [TransparentLC/cloud-clipboard#33]
请问 这个文件传输 是怎么传输的？
是通过正常的 上传 下载吗？文件是否保存在服务器上吗？
还是通过端对端 传输的吗？

**Comment by TransparentLC** [comment]
是使用上传下载的方式，在有效期内的文件会临时保存在服务器上。

并不会考虑做成端对端的形式，一方面是我对这个不太熟悉，另一方面是对于网页的形式以及我自己的使用习惯（打开网页，下载文件，关闭）还是上传下载更适合一些。
