### ISSUE TITLE
连接服务器失败，请点击工具栏上的“连接”图标重试

### ISSUE THREAD

**Issue by bkzy333** [TransparentLC/cloud-clipboard#36]
在群晖nas部署后一直提示“连接服务器失败，请点击工具栏上的“连接”图标重试”
json文件尝试过改为 "host":"0.0.0.0"和 "host":"127.0.0.1"都无法解决。

```json
{
    "server": {
        "host":"0.0.0.0",
        "port": 9501,
        "history": 10,
        "auth": false
    },
    "text": {
        "limit": 4096
    },
    "file": {
        "expire": 3600,
        "chunk": 2097152,
        "limit": 2684354560
    }
}
```
不知道是否跟反向代理设置有关，反向代理配置如下
![](https://img.zhendafang.top/i/2024/05/11/gtr0c0-3.webp)
![](https://img.zhendafang.top/i/2024/05/11/gutxxw-3.webp)
容器运行日志内容如下：

|**date**|**stream**|**content**|
| ---| --| ----------|
|**2024/05/11** **10:04:17**|**stdout**|**http://172.17.0.2:9501**|
|**2024/05/11** **10:04:17**|**stdout**|**eth0:**|
|**2024/05/11** **10:04:17**|**stdout**|**http://127.0.0.1:9501**|
|**2024/05/11** **10:04:17**|**stdout**|**lo:**|
|**2024/05/11** **10:04:17**|**stdout**|**Available** **at:**|
|**2024/05/11** **10:04:17**|**stdout**|**Server** **listening** **on** **port** **9501**  **...**|
|**2024/05/11** **10:04:17**|**stdout**|**Authorization** **code** **is** **disabled.**|
|**2024/05/11** **10:04:17**|**stdout**||
|**2024/05/11** **10:04:17**|**stdout**|**https://github.com/TransparentLC/cloud-clipboard**|
|**2024/05/11** **10:04:17**|**stdout**|**Cloud** **Clipboard** **node-1.2.0**|
|**2024/05/11** **10:04:17**|**stdout**||
|**2024/05/11** **09:59:49**|**stdout**|**http://172.17.0.2:9501**|
|**2024/05/11** **09:59:49**|**stdout**|**eth0:**|
|**2024/05/11** **09:59:49**|**stdout**|**http://127.0.0.1:9501**|
|**2024/05/11** **09:59:49**|**stdout**|**lo:**|
|**2024/05/11** **09:59:49**|**stdout**|**Available** **at:**|
|**2024/05/11** **09:59:49**|**stdout**|**Server** **listening** **on** **port** **9501**  **...**|
|**2024/05/11** **09:59:49**|**stdout**|**Authorization** **code** **is** **disabled.**|
|**2024/05/11** **09:59:49**|**stdout**||
|**2024/05/11** **09:59:49**|**stdout**|**https://github.com/TransparentLC/cloud-clipboard**|
|**2024/05/11** **09:59:49**|**stdout**|**Cloud** **Clipboard** **node-1.2.0**|
|**2024/05/11** **09:59:49**|**stdout**||
|**2024/05/11** **09:58:40**|**stdout**|**[90m** **at** **async** **handleMainPromise**  **(node:internal/modules/run_main:63:12)[39m**|
|**2024/05/11** **09:58:40**|**stdout**|**[90m** **at** **async** **Object.loadESM**  **(node:internal/process/esm_loader:68:5)[39m**|

![](https://img.zhendafang.top/i/2024/05/11/gsnlk6-3.webp)
‍![](https://img.zhendafang.top/i/2024/05/11/grvkoq-3.webp)

‍

‍

**Comment by TransparentLC** [comment]
#30
