### ISSUE TITLE
上传mp4文件下载会失败

### ISSUE THREAD

**Issue by neixgt** [TransparentLC/cloud-clipboard#37]
提示无法从网站上提取文件。从配置文件里也没看见可以修改限制的地方

**Comment by TransparentLC** [comment]
看描述是和 #34 相同的问题
我已经在 https://github.com/TransparentLC/cloud-clipboard/commit/fa6d51a6e6822e315d78d50839ba5b427d9bdb96#diff-8c915dfc5af4c4ca7cf70920ff09907b1e11857ebcfa7d71804d42c7b803a190 这里修复了
