### ISSUE TITLE
text长度限制失效

### ISSUE THREAD

**Issue by wufloor** [TransparentLC/cloud-clipboard#38]
text长度设置超过20048的数不生效，无论设置多大，超过20048长度的文字都发送失败

**Comment by TransparentLC** [comment]
koa-body 对 POST 的数据大小有[限制](https://github.com/koajs/koa-body#options)，默认是 56 KB，超过的话会直接返回 413 Payload Too Large。UTF-8 编码下一个汉字是 3 bytes，所以一次性发送大概两万个汉字就会超过限制。

作为参考，nginx 的[默认大小](https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size)是 1 MB，增加到这个值应该够用了。

**Comment by wufloor** [comment]
好的， 非常感谢。 作者回复及时，解决问题相当快，点赞
