### ISSUE TITLE
docker部署后  外网进去后显示无法连接上服务器

### ISSUE THREAD

**Issue by yhwilson** [TransparentLC/cloud-clipboard#41]
{
    "server": {
        "host": [
            "127.0.0.1",
            "::1"
        ],
        "port": 9501,
        "history": 50,
        "auth": 1211
    },
    "text": {
        "limit": 8192
    },
    "file": {
        "expire": 86400,
        "chunk": 5242000,
        "limit": 524288000
    }
}

这是我的配置文件。
我是通过lucky反向代理的https地址

**Comment by TransparentLC** [comment]
配置文件看样子没有什么问题，能否补充更多信息？

**Comment by yhwilson** [comment]
需要拿日志吗  路径是在哪个位置下面喃？

**Comment by TransparentLC** [comment]
比如反代相关的配置？打开页面时按一下 F12 然后看看 Network 那里的请求记录（特别是路径为 `/push` 的请求）？

**Comment by yhwilson** [comment]
![1719453720602](https://github.com/TransparentLC/cloud-clipboard/assets/39129716/25242aaa-c3f4-419e-a379-9f781dc4de11)

{"auth": true,"server": "ws://copy.wuyuelucky.fun:16666/push"}  
docker.m.daocloud.io 在这个上面拉取的镜像

**Comment by TransparentLC** [comment]
呃……不是说镜像站。

我根据 https://github.com/DaoCloud/public-image-mirror/issues/8752 推测你使用的镜像应该是 csmayi/lan-clip，也就是对反代的支持存在问题的那个。

请先尝试搜索现有 issue，参见 README 和 #30。

**Comment by yhwilson** [comment]
感谢  我去试下

**Comment by yhwilson** [comment]
{
"server": {
"host": [
"127.0.0.1",
"::1"
],
"port": 9501,
"history": 50,
"auth": 1211
},
"text": {
"limit": 8192
},
"file": {
"expire": 86400,
"chunk": 5242000,
"limit": 524288000
}
}

外网可以访问了  但是配置了auth却不生效  就很奇怪

**Comment by TransparentLC** [comment]
README：

> 可以将 server.auth 字段设为 true（随机生成六位密码）或**字符串**（自定义密码）来启用这个功能。
