### ISSUE TITLE
使用docker部署，怎么设置auth

### ISSUE THREAD

**Issue by xiaoyutx94** [TransparentLC/cloud-clipboard#43]
改了config里面的auth设置一个固定密码，也重新构建镜像了，但是好像没起作用，还是可以直接打开UI界面。
auth的作用不是输入密码才能查看剪贴板内容吗？

**Comment by xiaoyutx94** [comment]
有点缺陷，就是我在源码里改的server的auth，实际起作用的是server-node里的，但是源码里server-node里没有config文件

**Comment by TransparentLC** [comment]
`config.json` 被我写进 .gitignore 了，“实际起作用的是 server-node 里的”本来就是正常行为，因为 dockerfile 里写的就是 `WORKDIR /app/server-node`。

**Comment by xiaoyutx94** [comment]
> `config.json` 被我写进 .gitignore 了，“实际起作用的是 server-node 里的”本来就是正常行为，因为 dockerfile 里写的就是 `WORKDIR /app/server-node`。

了解，就是得到容器里面手动改一下。
