### ISSUE TITLE
我打包了一个arm64版本的docker镜像，大佬方便发布吗

### ISSUE THREAD

**Issue by shuaigekda** [TransparentLC/cloud-clipboard#44]

**Comment by TransparentLC** [comment]
感谢！直接在 README 里把你的镜像加上，然后提交 PR 就可以了。

（记得注明两个镜像的架构）

**Comment by shuaigekda** [comment]
大佬我不太会用GitHub，我推送到docker hub上了https://hub.docker.com/r/shuaigekda123/myclip
