### ISSUE TITLE
[feature request] how about add PWA support

### ISSUE THREAD

**Issue by yurenchen000** [TransparentLC/cloud-clipboard#45]
just add a manifest.json declearation,
  so that page can be add to desktop, 
  and  be run without browser address bar (fullscreen like a APP)

like the github does
https://github.com/manifest.json

<br>

run preview:
![run_app.png](https://github.com/user-attachments/assets/73af4c9e-5bec-4bd8-baa1-742e830049a8)

<br>

add to home screen:
![add_to_homescreen.png](https://github.com/user-attachments/assets/bc4b6630-d751-4084-aa22-6c60b345b413)

**Comment by yurenchen000** [comment]
1. manifest.json //144 size icon seems required
```json
{
  "name": "cloud_clip",
  "short_name": "cloud_clip",
  "start_url": "./",
  "display": "standalone",
  "icons": [
    {
      "sizes": "32x32",
      "src": "./favicon.ico"
    },
    {
      "src": "./favicon_144.png",
      "type": "image/png",
      "sizes": "144x144"
    },
    {
      "src": "./favicon.svg",
      "type": "image/svg",
      "sizes": "150x150"
    }
  ]
}
```

2. index.html //theme not required
```html
<!--
    <meta name="theme-color" content="#1e2327">
    <meta name="color-scheme" content="light dark" />
 -->
    <link rel="manifest" href="[manifest.json](https://clip.jios.top/manifest.json)">
```

**Comment by TransparentLC** [comment]
Just added manifest.json, no offline caching for PWA ...
