### ISSUE TITLE
history id maybe dup

### ISSUE THREAD

**Issue by yurenchen000** [TransparentLC/cloud-clipboard#46]
server-node from master branch.

with this history.json

```json
{
"file":[],
"receive":[
  {"id":0,"type":"text","room":"","content":"hello\n"},
  {"id":1,"type":"text","room":"","content":"world"},
  {"id":4,"type":"text","room":"","content":"ping 3"},
  {"id":6,"type":"text","room":"","content":"ping 4"}
]}
```
restart server, and post new item, history.json become
```json
{
"file":[],
"receive":[
  {"id":0,"type":"text","room":"","content":"hello\n"},
  {"id":1,"type":"text","room":"","content":"world"},
  {"id":4,"type":"text","room":"","content":"ping 3"},
  {"id":6,"type":"text","room":"","content":"ping 4"},
  {"id":4,"type":"text","room":"","content":"ping"}
]}
```

**the id:4 is dup**

**Comment by yurenchen000** [comment]
I guess when load from history.json
the messageQueue.counter need be the max of all exist id.

https://github.com/TransparentLC/cloud-clipboard/blob/9c869eca/server-node/app/http-router.js#L281

**Comment by TransparentLC** [comment]
The IDs in history.json are ignored now. They will be overwritten as 0, 1, 2 ... when the server starts and loads history.json.
