### ISSUE TITLE
如何一键清空？

### ISSUE THREAD

**Issue by star2k** [TransparentLC/cloud-clipboard#60]
内容多了，先清空，一个一个删除太费时间，如何一键清空？

**Comment by TransparentLC** [comment]
没有这个功能，之后有空的时候我可以考虑加上

**Comment by star2k** [comment]
> 没有这个功能，之后有空的时候我可以考虑加上

很好的项目，期待能更新，另外官方的docker hub链接有么，目前那边只找到一个非官方的镜像

**Comment by TransparentLC** [comment]
我自己并不使用 docker，所以目前确实没有什么官方 docker 镜像……
