### ISSUE TITLE
希望实现图片直接从页面上显示与复制

### ISSUE THREAD

**Issue by xjtu-blacksmith** [TransparentLC/cloud-clipboard#7]
对于一些图片文件（如临时截图），有时并不需要将其以文件形式储存下来，只希望和本地剪贴板一样作为媒介、实现软件间直接传递（例如，从网页上复制图片后粘贴到文字处理器当中）。

注意到目前的应用可以识别出图片文件并在页面上预览小图，希望能更进一步实现图片直接在网页上查看、复制，这样可能会更方便一些。

**Comment by TransparentLC** [comment]
已添加～

https://user-images.githubusercontent.com/47057319/197667755-60834db8-51cf-4cb3-b822-18ac6a9c4d1c.mp4

**Comment by xjtu-blacksmith** [comment]
新版本可以复制了，万分感谢！:+1:
